---
baseurl: http://log.mose.com
languageCode: en-us
title: Moselog
theme: hugo-theme-puremose
metaDataFormat: yaml
verbose: true
canonifyurls: true
params:
  description: Various rants from Mose.
  keywords: "mose, geek, french, taiwan, dev, devops, linux, opensource"
  github: mose
  twitter: mo5e
  cloudinary:
    prefix: http://res.cloudinary.com/mosepix/image/upload
  share:
    - facebook
    - google-plus
    - twitter
taxomonies:
  tag: tags
  origin: origins
  category: categories
permalinks:
  post: /:year/:month/:day/:title
