---
baseurl: "http://mose.github.io/mobla"
languageCode: "en-us"
title: "Mose Bla"
theme: puehurgo

params:
  description: "Personal rants from Mose."
  keywords: "mose, geek, french, taiwan"
  github: "mose"
  twitter: "mo5e"
